workflows:
  android-debug:
    name: Android Debug (recreate android/)
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - echo "Flutter & Java versions:"
      - flutter --version
      - java -version
      # IMPORTANT: remove old android folder so we get the new template
      - rm -rf android
      # Recreate a modern Android project (no iOS needed)
      - flutter create . --platforms=android --org com.example
      - flutter pub get
      # Build debug APK (more tolerant, good for first run)
      - flutter build apk --debug -v
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  android-release:
    name: Android Release (recreate android/)
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - echo "Flutter & Java versions:"
      - flutter --version
      - java -version
      # Recreate android/ to avoid old Gradle/AGP configs
      - rm -rf android
      - flutter create . --platforms=android --org com.example
      - flutter pub get
      # Accept SDK licenses (best-effort)
      - yes | sdkmanager --licenses || true
      # Build release with verbose logs and no shrink (avoids R8 issues)
      - flutter build apk --release -v --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
