workflows:
  android-debug:
    name: Android Debug (modern Gradle, CI wrapper)
    max_build_duration: 40
    environment:
      flutter: 3.35.6
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - android/.gradle

    scripts:
      - name: Print versions
        script: echo "Versions:" && flutter --version && java -version && uname -m

      - name: Pub get
        script: flutter pub get

      - name: Ensure Android host + Gradle wrapper + flutter_settings.gradle
        script: |
          # Always run 'flutter create' WITHOUT --overwrite.
          # It will create missing Android glue (flutter_settings.gradle, gradlew, etc.)
          # and will NOT clobber your existing files.
          flutter create . --platforms=android

          # Make sure the Gradle wrapper is executable
          chmod +x android/gradlew || true

      - name: Ensure local.properties has Flutter & Android SDK paths
        script: |
          cat > android/local.properties <<'EOF'
          sdk.dir=${ANDROID_SDK_ROOT}
          flutter.sdk=${FLUTTER_ROOT}
          EOF
          echo "Wrote android/local.properties:"
          cat android/local.properties

      - name: Build with Gradle
        script: |
          cd android
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon assembleDebug --stacktrace --info

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/reports/**/*
