workflows:
  android-debug-java:
    name: Android Debug (no Kotlin, new Gradle DSL)
    max_build_duration: 40
    environment:
      flutter: 3.35.6
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
    scripts:
      - echo "Versions:" && flutter --version && java -version

      # Regenerate Android host in **JAVA** (no Kotlin plugin needed)
      - flutter create . --platforms=android -a java --org com.example --overwrite

      - flutter pub get
      - yes | sdkmanager --licenses || true

      # settings.gradle (loads Flutter's Gradle plugin via includeBuild + plugins DSL)
      - |
        cat > android/settings.gradle <<'EOF'
        pluginManagement {
          def flutterSdkPath = System.getenv("FLUTTER_ROOT")
          if (flutterSdkPath == null && file("local.properties").exists()) {
            def props = new Properties()
            file("local.properties").withInputStream { props.load(it) }
            flutterSdkPath = props.getProperty("flutter.sdk")
          }
          if (flutterSdkPath == null) {
            throw new GradleException("Flutter SDK not found. Set FLUTTER_ROOT or flutter.sdk in local.properties")
          }
          includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")
          repositories {
            google()
            mavenCentral()
            gradlePluginPortal()
          }
        }
        plugins {
          id "dev.flutter.flutter-plugin-loader"
        }
        include(":app")
        EOF

      # Root android/build.gradle – AGP only (no Kotlin here)
      - |
        cat > android/build.gradle <<'EOF'
        plugins {
          id "com.android.application" version "8.6.1" apply false
          id "dev.flutter.flutter-plugin-loader" apply false
        }
        EOF

      # Module android/app/build.gradle – NO Kotlin plugin, NO kotlinOptions
      - |
        cat > android/app/build.gradle <<'EOF'
        plugins {
            id "com.android.application"
            id "dev.flutter.flutter-gradle-plugin"
        }

        android {
            namespace "com.example.pizza_ordering"
            compileSdk 34

            defaultConfig {
                applicationId "com.example.pizza_ordering"
                minSdk 21
                targetSdk 34
                versionCode 1
                versionName "1.0"
                multiDexEnabled true
            }

            buildTypes {
                release {
                    minifyEnabled false
                    signingConfig signingConfigs.debug
                }
            }

            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }

        flutter {
            source '../..'
        }
        EOF

      # Build
      - flutter build apk --debug --no-shrink -v

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
