workflows:
  android-debug:
    name: Android Debug (modern Gradle)
    max_build_duration: 40
    environment:
      flutter: 3.35.6
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - android/.gradle
    scripts:
      - echo "Versions:" && flutter --version && java -version && uname -m
      - flutter pub get
      - yes | sdkmanager --licenses || true
      - cd android
      - ./gradlew --no-daemon clean
      - ./gradlew --no-daemon assembleDebug --stacktrace --info
    publishing:
      artifacts:
        - android/app/build/outputs/**/*.apk
        - android/app/build/reports/**/*
