workflows:
  android-debug-java:
    name: Android Debug (no Kotlin, new Gradle DSL)
    max_build_duration: 40
    environment:
      flutter: 3.35.6
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
    scripts:
      - echo "Versions:" && flutter --version && java -version

      # 1) Regenerate Android host in **JAVA** (Kotlin-free)
      - flutter create . --platforms=android -a java --org com.example --overwrite

      - flutter pub get
      - yes | sdkmanager --licenses || true

      # 2) settings.gradle — plugin DSL + dependency resolution
      - |
        cat > android/settings.gradle <<'EOF'
        pluginManagement {
          // Resolve Flutter SDK path
          def flutterSdkPath = System.getenv("FLUTTER_ROOT")
          if (flutterSdkPath == null && file("local.properties").exists()) {
            def props = new Properties()
            file("local.properties").withInputStream { props.load(it) }
            flutterSdkPath = props.getProperty("flutter.sdk")
          }
          if (flutterSdkPath == null) {
            throw new GradleException("Flutter SDK not found. Set FLUTTER_ROOT or flutter.sdk in local.properties")
          }

          includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

          repositories {
            google()
            mavenCentral()
            gradlePluginPortal()
          }
        }

        // Let all modules resolve artifacts here
        dependencyResolutionManagement {
          repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
          repositories {
            google()
            mavenCentral()
          }
        }

        plugins {
          id "dev.flutter.flutter-plugin-loader"
        }

        include(":app")
        EOF

      # 3) Root android/build.gradle — AGP only (no Kotlin)
      - |
        cat > android/build.gradle <<'EOF'
        plugins {
          id "com.android.application" version "8.6.1" apply false
          id "dev.flutter.flutter-plugin-loader" apply false
        }
        EOF

      # 4) Module android/app/build.gradle — NO Kotlin plugin
      - |
        cat > android/app/build.gradle <<'EOF'
        plugins {
          id "com.android.application"
          id "dev.flutter.flutter-gradle-plugin"
        }

        android {
          namespace "com.example.pizza_ordering"
          compileSdk 34

          defaultConfig {
            applicationId "com.example.pizza_ordering"
            minSdk 21
            targetSdk 34
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
          }

          buildTypes {
            release {
              minifyEnabled false
              signingConfig signingConfigs.debug
            }
          }

          compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
          }
        }

        flutter {
          source '../..'
        }
        EOF

      # 5) Quick sanity check: show headers to confirm NO Kotlin plugin anywhere
      - echo "----- android/build.gradle -----" && sed -n '1,30p' android/build.gradle
      - echo "----- android/app/build.gradle -----" && sed -n '1,30p' android/app/build.gradle

      # 6) Build with Gradle (clearer errors than 'flutter build')
      - cd android && ./gradlew :app:assembleDebug --no-daemon --stacktrace --warning-mode all

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
