workflows:
  android-debug-fixed:
    name: Android Debug (APK output fixed)
    max_build_duration: 40
    environment:
      flutter: 3.35.6
      java: 17
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
    scripts:
      - echo "Versions:" && flutter --version && java -version
      - flutter create . --platforms=android --org com.example --overwrite
      - flutter pub get
      - yes | sdkmanager --licenses || true
      - |
        set -e
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug -x lint --no-daemon --stacktrace --warning-mode all --console=plain
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
